# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: mongo-config
# data:
#   APP_PORT: "8080"
#   MONGO_HOST: mongodb

apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  APP_PORT: "8080"
  MONGO_HOST: mongodb
  mongo.conf: |
    storage:
      dbPath: /data/db