apiVersion: v1 # versi api kubernetes
kind: Service # menunjukan jenis object: service (berfungsi untuk memungkinkan komunikasi antara pod (internal)  atau antar pod dari dunia luar (external))
metadata: # informasi tambahan object
  namespace: submission2 # menggunakan object ini akan ditempatkan di namespace submission2
  name: karsajobs-ui
  labels: # mengelompokan object dengan label
    app: karsajobs-ui
spec:
  ports:
  - port: 8000 # Port Service yang diekspos ke internal cluster.
    targetPort: 8000 # port yang digunakan oleh Container di Port
    nodePort: 30000 # Port pada node host (misalnya Docker Desktop / Minikube) yang digunakan untuk akses dari luar (misalnya localhost:30001 di browser).
  selector: # service akan mengarahkan ke pod yang memiliki label app=karsajobs-ui, dan tier=frontend
    app: karsajobs-ui
    tier: frontend
  type: NodePort # menentukan type service: NodePort (menggunakan port node host), ClusterIP (menggunakan port internal cluster)