apiVersion: v1
kind: Service
metadata:
  name: karsajobs-ui
  labels:
    app: karsajobs-ui
spec:
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000
  selector:
    app: karsajobs-ui
    tier: frontend
  type: NodePort