version: 2.1
jobs:
  # untuk karsajobs dan karsajobs-ui
  lint-dockerfile: # Lint Dockerfile
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run:
          name: Lint Dockerfile
          command: |
            curl -Lo ./hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
            chmod +x ./hadolint
            ./hadolint Dockerfile

  # untuk karsajobs
  test-app-karsajobs: # Test App for karsajobs
    docker:
      - image: golang:1.21
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            go mod download
      - run:
          name: Test App
          command: |
            go test -v -short --count=1 $(go list ./...)
  build-app-karsajobs:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and Push App
          command: |
            echo "TOKEN_REGISTRY=${GITHUB_TOKEN}" >> .envtoken
            cat .envtoken
            chmod +x ./build_push_image_karsajobs.sh
            ./build_push_image_karsajobs.sh

  # untuk karsajobs-ui
  build-app-karsajobs-ui:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and Push App
          command: |
            echo "TOKEN_REGISTRY=${GITHUB_TOKEN}" >> .envtoken
            cat .envtoken
            chmod +x ./build_push_image_karsajobs_ui.sh
            ./build_push_image_karsajobs_ui.sh

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - lint-dockerfile:
          filters:
            branches:
              only: 
                - karsajobs
                - karsajobs-ui
      - test-app-karsajobs:
          requires:
            - lint-dockerfile
          filters:
            branches:
              only: karsajobs
      - build-app-karsajobs:
          requires:
            - test-app-karsajobs
          filters:
            branches:
              only: karsajobs
      - build-app-karsajobs-ui:
          requires:
            - lint-dockerfile
          filters:
            branches:
              only: karsajobs-ui