version: 2.1
orbs:
  go: circleci/golang@1.0.0
jobs:
  lint-dockerfile:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run:
          name: Lint Dockerfile
          command: |
            curl -Lo /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
            chmod +x /usr/local/bin/hadolint
            hadolint Dockerfile

  test-app:
    docker:
      - image: golang:1.21
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            go mod download
      - run:
          name: Test App
          command: |
            go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and Push App
          command: |
            echo "TOKEN_REGISTRY=${TOKEN_REGISTRY}" >> .envtoken
            ./build_push_image_karsajobs.sh

  build-app-karsajobs-ui:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and Push App
          command: |
            echo "TOKEN_REGISTRY=${TOKEN_REGISTRY}" >> .envtoken
            ./build_push_image_karsajobs_ui.sh

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - lint-dockerfile
      - test-app:
          requires:
            - lint-dockerfile
      - build-app-karsajobs:
          requires:
            - test-app
          filters:
            branches:
              only: karsajobs
      - build-app-karsajobs-ui:
          requires:
            - lint-dockerfile
          filters:
            branches:
              only: karsajobs-ui