apiVersion: v1 # versi api kubernetes
kind: Service # menunjukan jenis object: service (berfungsi untuk memungkinkan komunikasi antara pod (internal)  atau antar pod dari dunia luar (external))
metadata: # informasi tambahan object
  name: karsajobs
  labels: # mengelompokan object dengan label
    app: karsajobs
spec:
  ports:
  - port: 8080 # Port Service yang diekspos ke internal cluster.
    targetPort: 8080 # port yang digunakan oleh Container di Port
    nodePort: 30001 # Port pada node host (misalnya Docker Desktop / Minikube) yang digunakan untuk akses dari luar (misalnya localhost:30001 di browser).
  selector: # service akan mengarahkan ke pod yang memiliki label app=karsajobs, dan tier=backend
    app: karsajobs
    tier: backend
  type: NodePort # menentukan type service: NodePort (menggunakan port node host), ClusterIP (menggunakan port internal cluster)