apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs
      tier: backend
  template:
    metadata:
      labels:
        app: karsajobs
        tier: backend
    spec:
      containers:
      - name: karsajobs
        image: ghcr.io/ariafatah0711/karsajobs:latest
        ports:
          - containerPort: 8080
        env:
          - name: APP_PORT
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: APP_PORT
          - name: MONGO_HOST
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: MONGO_HOST
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGO_USER
          - name: MONGO_PASS
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGO_PASS