version: "2"

# service / container
services:
  item-app:
    image: ghcr.io/ariafatah0711/item-app:v1 # image container
    container_name: item-app # name container
    ports:
      - 80:8080 # bind / menghubungkan port host 80 ke port container 8080
    networks:
      - item-app # menghubungkan container dengan network yang samaz
    restart: always # mengaktifkan kembali container ketika host dinyalakan kembali

  item-db:
    image: mongo:3
    container_name: item-db
    networks:
      - item-app
    volumes:
      - app-db:/data/db # Volume Docker untuk menyimpan data database di dalam app-db supaya data tetap ada
    restart: always
  
# volumes
volumes:
  app-db: # volume yang dibuat docker yang berfungsi untuk persistence storage

# networks
networks:
  item-app: # network yang digunakan untuk menghubungkan beberapa container