apiVersion: v1 # versi api kubernetes
kind: PersistentVolume # menunjukan jenis object: PersistentVolume (objek ini menyediakan resource storage fisik di cluster)
metadata: # informasi tambahan object
  # namespace: submission2
  name: mongo-pv
  labels: # mengelompokan object dengan label
    type: local # label tambahan (opsional), bisa digunakan untuk seleksi PV berdasarkan jenis/tipe
spec:
  storageClassName: manual # mengelompokkan PV dan PVC agar cocok satu sama lain secara manual
  capacity:
    storage: 1Gi # kapasitas storage yang disediakan (1 Gigabyte)
  accessModes:
    - ReadWriteOnce # hanya bisa dibaca dan ditulis oleh satu node (umum digunakan)
  hostPath: # hostPath hanya cocok untuk local testing seperti di Minikube atau Docker Desktop. Di production biasanya pakai cloud storage (EBS, GCE, dll).
    path: /mnt/data/ # path di node host (misalnya Minikube atau Docker Desktop) yang akan digunakan sebagai volume

---

apiVersion: v1 # versi api kubernetes
kind: PersistentVolumeClaim # menunjukan jenis object: PersistentVolumeClaim (objek yang digunakan pod untuk 'meminta' storage dari PV)
metadata: # informasi tambahan object
  # namespace: submission2
  name: mongo-pvc
spec:
  storageClassName: manual # harus cocok dengan storageClassName PV agar bisa saling terhubung
  accessModes:
    - ReadWriteOnce # sama seperti PV: hanya bisa dibaca dan ditulis oleh satu node
  resources:
    requests:
      storage: 1Gi # kapasitas storage yang diminta (harus sama atau kurang dari PV)