apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_ROOT_USERNAME: ZGljb2Rpbmc=
  MONGO_ROOT_PASSWORD: ZGljb2Rpbmc=
# stringData:
  # MONGO_ROOT_USERNAME: dicoding
  # MONGO_ROOT_PASSWORD: dicoding