apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
# data:
#   username: ZGljb2Rpbmc=
#   password: ZGljb2Rpbmc=
stringData:
  MONGO_ROOT_USERNAME: dicoding
  MONGO_ROOT_PASSWORD: dicoding