apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
    kind: database
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb
    tier: database
  clusterIP: None