apiVersion: v1 # versi api kubernetes
kind: ConfigMap # menunjukan jenis object: ConfigMap (menyimpan konfigurasi non-rahasia dalam bentuk key-value)
metadata: # informasi tambahan object
  namespace: submission2
  name: mongo-config
data: # data yang akan disimpan dalam ConfigMap
  APP_PORT: "8080"
  MONGO_HOST: mongodb
  mongo.conf: |
    storage:
      dbPath: /data/db