apiVersion: apps/v1 # versi 
kind: StatefulSet
metadata:
  # namespace: submission2
  name: mongodb
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
      tier: database
  serviceName: mongodb
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      # namespace: submission2
      labels:
        app: mongodb
        tier: database
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        # command: ["mongod", "--config", "/config/mongo.conf"]
        env:
        - name: MONGO_INITDB_ROOT_USERNAME_FILE
          value: "/etc/mongo-credentials/MONGO_ROOT_USERNAME" # Nama file tempat menyimpan username root MongoDB
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE
          value: "/etc/mongo-credentials/MONGO_ROOT_PASSWORD" # Nama file tempat menyimpan password root MongoDB
        volumeMounts:
          - name: data-volume
            mountPath: /data/db # Path tempat menyimpan data MongoDB
          - name: config-volume
            mountPath: /config # Path tempat menyimpan konfigurasi MongoDB
          - name: credentials-volume
            mountPath: /etc/mongo-credentials # Path tempat menyimpan credentials MongoDB
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: mongo-pvc # Mengacu pada nama claim
        - name: config-volume
          configMap:
            name: mongo-config # Mengacu pada nama ConfigMap
        - name: credentials-volume
          secret:
            secretName: mongo-secret # Mengacu pada nama Secret