apiVersion: v1 # versi api kubernetes
kind: Secret # menunjukan jenis object: Secret (menyimpan data sensitif seperti password atau token)
metadata: # informasi tambahan object
  namespace: submission2
  name: mongo-secret
type: Opaque # artinya isinya adalah data arbitrer (biasa digunakan untuk password, token, dsb).
data: # Data rahasia yang disimpan dalam bentuk base64.
  MONGO_ROOT_USERNAME: YWRtaW4= # admin
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA== # supersecretpassword (properly encoded without newlines)
# stringData: # Data rahasia yang disimpan dalam bentuk String
  # MONGO_ROOT_USERNAME: admin
  # MONGO_ROOT_PASSWORD: supersecretpassword