apiVersion: v1 # versi api kubernetes
kind: ConfigMap # menunjukan jenis object: ConfigMap (menyimpan konfigurasi non-rahasia dalam bentuk key-value)
metadata: # informasi tambahan object
  namespace: submission2 # menggunakan object ini akan ditempatkan di namespace submission2
  name: mongo-config
data: # data yang akan disimpan dalam ConfigMap
  APP_PORT: "8080" # Menyimpan konfigurasi port aplikasi dalam bentuk string "8080".
  MONGO_HOST: mongodb # Menunjukkan host atau service name dari MongoDB.
  mongo.conf: | # Ini menyimpan file konfigurasi MongoDB dalam bentuk YAML multi-line (ditandai dengan |).
    storage:
      dbPath: /data/db