apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
# data:
#   username: ZGljb2Rpbmc=
#   password: ZGljb2Rpbmc=
stringData:
  # MONGO_USER: dicoding
  # MONGO_PASS: dicoding
  MONGO_ROOT_USERNAME: dicoding # Data rahasia (username) yang akan disimpan dalam Secret, hasil dari encoding base64 dari "admin"
  MONGO_ROOT_PASSWORD: dicoding # Data rahasia (password) yang akan disimpan dalam Secret, hasil dari encoding base64 dari "supersecretpassword"