apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: submission3
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: ghcr.io/ariafatah0711/order-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: AMQP_URL
              value: amqp://guest:guest@rabbitmq.submission3.svc.cluster.local:5672
              # value: amqp://guest:guest@rabbitmq:5672
              # value: amqp://admin:admin123@rabbitmq:5672
              # value: amqp://admin:admin123@192.168.49.2:30006
            - name: PORT
              value: "3000"

---

apiVersion: v1
kind: Service
metadata:
  namespace: submission3
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30010
  type: NodePort