apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: submission3
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.8-management-alpine
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-data
            - mountPath: /var/log/rabbitmq
              name: rabbitmq-log
      volumes:    
          - name: rabbitmq-data
            emptyDir: {}
          - name: rabbitmq-log
            emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  namespace: submission3
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      nodePort: 30006
    - name: management
      port: 15672
      targetPort: 15672
      nodePort: 30007
  type: NodePort