apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: submission3
  name: shipping-service
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command: ['sh', '-c', 'for i in $(seq 1 30); do nc -z rabbitmq 5672 && exit 0 || sleep 2; done; exit 1']
      containers:
        - name: shipping-service
          image: ghcr.io/ariafatah0711/shipping-service:latest
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: production
            - name: AMQP_URL
              value: amqp://guest:guest@rabbitmq.submission3.svc.cluster.local:5672
              # value: amqp://guest:guest@rabbitmq:5672
              # value: amqp://admin:admin123@rabbitmq:5672
              # value: amqp://admin:admin123@192.168.49.2:30006
            - name: PORT
              value: "3001"
          readinessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  namespace: submission3
  name: shipping-service
spec:
  selector:
    app: shipping-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP